name: Question Template
description: YAML Tamplate Description
title: "[Question]: 질문 제목"
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-question
    attributes:
      label: 질문 내용
      description: 관련된 이슈가 있다면 함께 적어주세요!
      placeholder: Question Content
      value: |
        질문 내용
        
        ### 관련된 이슈
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 시도해본 것 or 찾아본 래퍼런스
      description: 사진을 함께 첨부하면 좋아요!
      value: |
        ## 시도해본 것
        - 
        
        ## 찾아본 래퍼런스
        - 
    validations:
      required: false  
